### ISSUE TITLE
Conditional Action Boolean Condition not catching "true"

### ISSUE THREAD

**Issue by JALsnipe** [bap2000/jenkins-flexible-publish-plugin#2]
Hi, I'm trying to use your plugin to trigger an upload to testflight with a specific build parameter.  I set the boolean QA equal to true to enable the flexible publish action.

```
Started by user JALsnipe
Building in workspace /Users/Shared/Jenkins/Home/jobs/myApp/workspace
Fetching changes from the remote Git repository
Fetching upstream changes from git@github.com:JALsnipe/myApp.git
Checking out Revision [version] (origin/development)
Run condition [Boolean condition] enabling prebuild for step [Upload to Testflight]
[workspace] $ /bin/sh -xe /var/folders/87/04w7gk1s23sdc9szb12w9sr80000gp/T/hudson5004177172413578404.sh
+ echo the value of QA is true
the value of QA is true
[Boolean condition] checking [QA] against [^(1|y|yes|t|true|on|run)$] (origin token: QA)
Run condition [Boolean condition] preventing perform for step [Upload to Testflight]
```

Note that I echo the value of QA in the Execute Shell section, and it prints as true.  However, I still get the `Run condition [Boolean condition] preventing perform for step [Upload to Testflight]` error.

Any idea what could be wrong?  Thanks!

**Comment by devinair** [comment]
Hi ,

In the Token section in  the jenkins job configuration, you have to specify $Parametername instead of Parameter name. Then only the boolean value will be taken correctly.
![capture](https://cloud.githubusercontent.com/assets/12840909/8100965/f35074a8-102f-11e5-8439-0293a3eb48c4.JPG)

Hope it helps,

Thanks
Devi

**Comment by JALsnipe** [comment]
Thanks @devinair!

**Comment by gotoworld** [comment]
${ENV,var="false"}
